### PR TITLE
Added Orb

### PR DESCRIPTION
**Pull request by Aethedor**

### CODE REVIEW

**Comment by syxanash** [comment]
Hi @Aethedor,
Thanks for your submission, unfortunately I won't put on the list websites that are not immediately playable or hidden behind a registration forms/login pages. If you have a demo page that would be great :)
Good luck with the development!

**Comment by Aethedor** [comment]
Yeah, Orb is different than the rest. Orb is a real web desktop, a real 
web OS with a back-end, which of course requires a login. The rest on 
your list are more like web desktop jokes and funny demos. So, if that's 
your selection criterion, than it's indeed better to not put Orb on that 
list.

P.S.
Typing 'demo' twice isn't so hard, now is it?

**Comment by syxanash** [comment]
Hey, I really like the idea, I think is a great side project to work on and I'm happy you made it open source too!
Sorry I reconsidered my initial choice, I'll add a note with the login credentials in the list :)

**Comment by syxanash** [comment]
I would only like to give you a small feedback: I'd give a hint with the credentials in the landing page I think some users will simply navigate away otherwise.

Thanks again for your submission!

**Pull request merged**
