### PR TITLE
Add Win7 Simu

### PR DESCRIPTION
**Pull request by khang-nd**

### CODE REVIEW

**Comment by syxanash** [comment]
Hi Khang! I think what you did there is very impressive, congratulations!
I'll definitely add this website to this list, if I may add a small feedback the ads that appear throughout the webapp they seem a bit too invasive and might ruin the whole experience.
Thanks again for adding your project!

**Comment by khang-nd** [comment]
Thanks Simone. That I did consider and tried to setup the ads to be as blending with the experience as possible.

**Comment by aaxx3443xxaa** [comment]
كيف افهم هذا البرنامج وندوز

**Comment by aaxx3443xxaa** [comment]
كيف اطور من نفسي

**Comment by aaxx3443xxaa** [comment]
اعلاني بحث عن بيع الاغنام والماعز البلدي

**Comment by aaxx3443xxaa** [comment]
كيف اخدمك

**Pull request merged**
