### PR TITLE
Add Vuindows

### PR DESCRIPTION
**Pull request by marcmascarell**
Let me know if I can add it like that or you want exactly the same format than others

### CODE REVIEW

**Comment by syxanash** [comment]
Hi @marcmascarell!
Thank you for your submission I really dig your work, really great job!

I'll add it to the list :)
Do you mind if for the moment I just add the main link? I'm planning to add the source code later on since many projects in this list are open source!

**Comment by marcmascarell** [comment]
Thank you! 

Ok, it's fine (:

**Comment by syxanash** [comment]
Thanks!
I'll keep you posted when I make this change :D

**Comment by syxanash** [comment]
I've included the link to your repo in the README.md

**Comment by marcmascarell** [comment]
Thank you mate!

**Pull request merged**
